name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          mvn clean install
          mvn package -DskipTests
          ls -lah target/  # Verify JAR exists

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app/target/"
          overwrite: true
          strip_components: 0

      - name: Run JAR on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo chmod +x /home/ubuntu/app/target/demo-0.0.1-SNAPSHOT.jar
            
            # Kill old process running on port 80 if any
            sudo fuser -k 80/tcp || true
            
            # Run the JAR file
            nohup sudo java -jar /home/ubuntu/app/target/demo-0.0.1-SNAPSHOT.jar --server.port=80 > /home/ubuntu/app/app.log 2>&1 &
            
            # Wait for the app to start
            sleep 15

            # Check if the application is running
            if curl -I http://localhost:80; then
              echo "✅ Application deployed successfully!"
            else
              echo "❌ Application failed to start."
              exit 1
            fi
