name: Deploy Spring Boot to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: |
          mvn clean install
          mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/demo-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app/"
          overwrite: true
          strip_components: 0

      - name: Verify JAR Exists on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -f "/home/ubuntu/app/demo-0.0.1-SNAPSHOT.jar" ]; then
              echo "✅ JAR file successfully transferred."
            else
              echo "❌ JAR file not found on EC2. SCP may have failed."
              exit 1
            fi

      - name: Deploy JAR on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo mkdir -p /home/ubuntu/app
            sudo chmod 777 /home/ubuntu/app
            
            # Move and rename JAR
            sudo mv /home/ubuntu/app/demo-0.0.1-SNAPSHOT.jar /home/ubuntu/app/app.jar
            
            # Kill old process
            sudo fuser -k 80/tcp || true
            
            # Start new process
            nohup java -jar /home/ubuntu/app/app.jar --server.port=80 > /home/ubuntu/app/app.log 2>&1 &

            # Verify the app is running
            sleep 10
            if curl -I http://localhost:80; then
              echo "✅ Application deployed successfully!"
            else
              echo "❌ Application failed to start."
              exit 1
            fi
